image: repo.adeo.no:5443/soknad/soknad-html-generator
team: team-soknad
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 9000
healthcheck:
  liveness:
    path: api/ping
  readiness:
    path: api/ping
prometheus:
  enabled: false
ingress:
  enabled: false
resources:
  limits:
    cpu: 2
    memory: 512Mi
  requests:
    memory: 256Mi