apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknad-html-generator
  namespace: default
  labels:
    team: teamfamilie

spec:
  image: repo.adeo.no:5443/soknad-html-generator:RELEASE_VERSION
  port: 9000
  liveness:
    path: /api/ping
  readiness:
    path: /api/ping
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
  ingresses:
    - "https://soknad-html-generator.nais.oera.no/"
