version: '3'

services:
  ci-test-server:
    image: navikt/node-express:1.0.0
    volumes:
      - ../dev:/var/dist
    ports:
      - 9000:9000
    entrypoint:
      - node
      - /var/dist/main.js
  jest-image-snapshot:
    image: repo.adeo.no:5443/soknad/soknad-docker-jest-image-snapshot:0.0.2
    depends_on:
      - ci-test-server
    volumes:
      - ./jest-image-snapshot/tests:/app/tests
      - ./jest-image-snapshot/baseline:/app/baseline
