version: '3'

services:
  test-server:
    build: ./../
    ports:
      - 9000:9000
    networks: 
      - default
  gemini:
    image: repo.adeo.no:5443/soknad/soknad-docker-gemini:1.0.0
    depends_on:
      - test-server
      - chrome
    volumes:
      - ./gemini:/var/gemini/
      - ./reports/:/reports/
  chrome:
    image: selenium/standalone-chrome:3.14.0
    ports:
      - 4444:4444
