apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: soknad-html-generator
  namespace: teamfamilie
  labels:
    team: teamfamilie
   
spec:
  image: {{image}}
  port: 9000
  liveness:
    path: /api/ping
  readiness:
    path: /api/ping
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
  ingresses:
{{#each ingresses as |url|}}
    - {{url}}
{{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: soknad-kontantstotte-api