name: Build&deploy to dev and prod

on:
  push:
    branches:
      - 'master'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/soknad-kontantstotte-html:${{ github.sha }}
  IMAGE_LATEST: docker.pkg.github.com/${{ github.repository }}/soknad-kontantstotte-html:latest
  VERSION: soknad-kontantstotte-html:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn
          yarn build
          yarn test:ci
          docker build . -t ${IMAGE} -t ${IMAGE_LATEST}
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
          docker push ${IMAGE_LATEST} 
  deploy:
    name: Deploy to NAIS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy til dev-sbs
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-sbs
          RESOURCE: app-preprod.yaml
          VAR: VERSION=${{ env.VERSION }}
      - name: Deploy til prod-sbs
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-sbs
          RESOURCE: app-prod.yaml
          VAR: VERSION=${{ env.VERSION }}