name: Build&deploy to dev

on:
  pull_request:
  workflow_dispatch:

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/soknad-kontantstotte-html:${{ github.sha }}
  VERSION: soknad-kontantstotte-html:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn
          yarn build
          yarn test:ci
          docker build . -t ${IMAGE}
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
  deploy:
    name: Deploy to NAIS (dev-sbs)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-sbs
          RESOURCE: app-preprod.yaml
          VAR: VERSION=${{ env.VERSION }}
